version: '3.7'
services:
    airflow:
      build:
        dockerfile: Dockerfile
        context: .
      ports:
          - "8080:8080"
      healthcheck:
          test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
          interval: 30s
          timeout: 30s
          retries: 3
