version: '3.7'
services:
    postgres:
      image: postgres:9.6
      environment:
        - POSTGRES_USER=airflow
        - POSTGRES_PASSWORD=airflow
        - POSTGRES_DB=airflow
      logging:
        options:
            max-size: 10m
            max-file: "3"
    airflow:
      depends_on:
        - postgres
      build:
        dockerfile: Dockerfile
        context: .
      environment:
        - LOAD_EX=y
        - EXECUTOR=Local
      logging:
        options:
          max-size: 10m
          max-file: "3"
      ports:
        - "8080:8080"
      healthcheck:
          test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
          interval: 30s
          timeout: 30s
          retries: 3
